### ISSUE TITLE
[Compatibility Request]: Map Writer

### ISSUE THREAD

**Issue by irontom10** [GTMEGA/EndlessIDs#146]
### OS

Windows

### GPU

AMD

### Modpack (Optional)

custom

### Game log

https://mclo.gs/hwooY5z

### Description

java.lang.UnsupportedOperationException: A mod that is incompatible with EndlessIDs has tried to access the block array of a chunk like in vanilla! Crashing in fear of potential world corruption!
Please report this issue on https://github.com/FalsePattern/EndlessIDs ASAP!
	at net.minecraft.world.chunk.storage.ExtendedBlockStorage.emergencyCrash(SourceFile:676)
	at net.minecraft.world.chunk.storage.ExtendedBlockStorage.handler$zzn000$endlessids$crashLSBArray(SourceFile:856)
	at net.minecraft.world.chunk.storage.ExtendedBlockStorage.func_76658_g(SourceFile)
	at mapwriter.ChunkManager.copyToMwChunk(ChunkManager.java:48)
	at mapwriter.ChunkManager.updateSurfaceChunks(ChunkManager.java:122)
	at mapwriter.ChunkManager.onTick(ChunkManager.java:137)
	at mapwriter.Mw.onTick(Mw.java:630)
	at mapwriter.forge.MwForge.renderMap(MwForge.java:55)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_13_MwForge_renderMap_Post.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:899)
	at net.minecraftforge.client.GuiIngameForge.func_73830_a(GuiIngameForge.java:176)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1038)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)

**Comment by irontom10** [comment]
patch required for map writer

**Comment by FalsePattern** [comment]
Fixed, use this mapwriter fork: https://github.com/FalsePattern/mapwriter
