### ISSUE TITLE
[Bug]: Data value id is too big with 34!

### ISSUE THREAD

**Issue by dayd21git** [GTMEGA/EndlessIDs#154]
### Game log
```
Time: 10/26/23 4:58 PM
Description: Ticking memory connection

java.lang.IllegalArgumentException: Data value id is too big with 34! (Max is 31)
	at net.minecraft.entity.DataWatcher.func_75682_a(SourceFile:61)
	at net.nevermine.resource.energy.energyHelper.<init>(energyHelper.java:18)
	at net.nevermine.resource.energy.energyHelper.addProperties(energyHelper.java:28)
	at net.nevermine.event.player.EntityConstructorEvent.onEntityConstructing(EntityConstructorEvent.java:19)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_253_EntityConstructorEvent_onEntityConstructing_EntityConstructing.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.entity.Entity.<init>(Entity.java:179)
	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:119)
	at net.minecraft.entity.player.EntityPlayer.<init>(EntityPlayer.java:141)
	at net.minecraft.entity.player.EntityPlayerMP.<init>(EntityPlayerMP.java:138)
	at net.minecraft.server.management.ServerConfigurationManager.func_148545_a(ServerConfigurationManager.java:410)
	at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:101)
	at net.minecraft.server.network.NetHandlerLoginServer.func_147233_a(NetHandlerLoginServer.java:60)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:215)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
	```

**Comment by FalsePattern** [comment]
Fixed
