### ISSUE TITLE
[Compatibility Request]: Emergency Crash when HBM is trying to create the Crater biome after nuke explosion

### ISSUE THREAD

**Issue by Kotorybeusz** [GTMEGA/EndlessIDs#177]
### Other mod's name

HBM Nuclear Tech Mod

### Other mod's homepage

https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT?tab=readme-ov-file

### Other mod's license

LGPLv3

### Game log

Description: Ticking entity

java.lang.UnsupportedOperationException: A mod that is incompatible with EndlessIDs has tried to access the biome array of a chunk like in vanilla! Crashing in fear of potential world corruption!
Please report this issue on https://github.com/FalsePattern/EndlessIDs ASAP!
	at net.minecraft.world.chunk.Chunk.emergencyCrash(Chunk.java:1628)
	at net.minecraft.world.chunk.Chunk.handler$zzl000$crashGetBiomeArray(Chunk.java:1642)
	at net.minecraft.world.chunk.Chunk.func_76605_m(Chunk.java)
	at com.hbm.world.WorldUtil.setBiome(WorldUtil.java:23)
	at com.hbm.entity.effect.EntityFalloutRain.func_70071_h_(EntityFalloutRain.java:72)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.chunk.Chunk.emergencyCrash(Chunk.java:1628)
	at net.minecraft.world.chunk.Chunk.handler$zzl000$crashGetBiomeArray(Chunk.java:1642)
	at net.minecraft.world.chunk.Chunk.func_76605_m(Chunk.java)
	at com.hbm.world.WorldUtil.setBiome(WorldUtil.java:23)
	at com.hbm.entity.effect.EntityFalloutRain.func_70071_h_(EntityFalloutRain.java:72)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at net.minecraft.world.World.func_72939_s(World.java:1887)

-- Entity being ticked --
Details:
	Entity Type: hbm.entity_fallout (com.hbm.entity.effect.EntityFalloutRain)
	Entity ID: 79220
	Entity Name: entity.hbm.entity_fallout.name
	Entity's Exact location: -404.50, 66.50, 19.50
	Entity's Block location: World: (-405,66,19), Chunk: (at 11,4,3 in -26,1; contains blocks -416,0,16 to -401,255,31), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
Stacktrace:
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)

### Description

After a nuke explodes HBM is trying to create a Crater biome in place of explosion which causes EndlessIDs to emergency crash. At least thats what I think happens

**Comment by FalsePattern** [comment]
Update HBM
