### ISSUE TITLE
[Compatibility Request]: nucleardust generated by NTM space caused bug which has tried to access the biome array of a chunk like in vanilla

### ISSUE THREAD

**Issue by hbmlover** [GTMEGA/EndlessIDs#199]
### Other mod's name

NTM space

### Other mod's homepage

https://github.com/HbmMods/Hbm-s-Nuclear-Tech-GIT

### Other mod's license

GPLv3

### Game log

---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 24-8-16 下午6:10
Description: Ticking entity

java.lang.UnsupportedOperationException: A mod that is incompatible with EndlessIDs has tried to access the biome array of a chunk like in vanilla! Crashing in fear of potential world corruption!
Please report this issue on https://github.com/FalsePattern/EndlessIDs ASAP!
	at net.minecraft.world.chunk.Chunk.eid$emergencyCrash(Chunk.java:1654)
	at net.minecraft.world.chunk.Chunk.handler$zcb000$endlessids$crashGetBiomeArray(Chunk.java:1668)
	at net.minecraft.world.chunk.Chunk.func_76605_m(Chunk.java)
	at com.hbm.world.WorldUtil.setBiome(WorldUtil.java:23)
	at com.hbm.entity.effect.EntityFalloutRain.func_70071_h_(EntityFalloutRain.java:73)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at WorldServerOF.func_72870_g(WorldServerOF.java:347)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.world.chunk.Chunk.eid$emergencyCrash(Chunk.java:1654)
	at net.minecraft.world.chunk.Chunk.handler$zcb000$endlessids$crashGetBiomeArray(Chunk.java:1668)
	at net.minecraft.world.chunk.Chunk.func_76605_m(Chunk.java)
	at com.hbm.world.WorldUtil.setBiome(WorldUtil.java:23)
	at com.hbm.entity.effect.EntityFalloutRain.func_70071_h_(EntityFalloutRain.java:73)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at WorldServerOF.func_72870_g(WorldServerOF.java:347)
	at net.minecraft.world.World.func_72939_s(World.java:1887)

-- Entity being ticked --
Details:
	Entity Type: hbm.entity_fallout (com.hbm.entity.effect.EntityFalloutRain)
	Entity ID: 11259
	Entity Name: entity.hbm.entity_fallout.name
	Entity's Exact location: -111.50, 73.50, 87.50
	Entity's Block location: World: (-112,73,87), Chunk: (at 0,4,7 in -7,5; contains blocks -112,0,80 to -97,255,95), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Entity's Momentum: 0.00, 0.00, 0.00
Stacktrace:
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)

-- Affected level --
Details:
	Level name: new world
	All players: 1 total; [EntityPlayerMP['gman'/3129, l='new world', x=-136.76, y=106.28, z=20.27]]
	Chunk stats: ServerChunkCache: 811 Drop: 0
	Level seed: 4785246154366216421
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-107,64,76), Chunk: (at 5,4,12 in -7,4; contains blocks -112,0,64 to -97,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 685 game time, 685 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 134704 (now: false), thunder time: 160079 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 1.8.0_421, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1172108032 bytes (1117 MB) / 3152019456 bytes (3006 MB) up to 11488198656 bytes (10956 MB)
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn1643m -Xmx10956m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 155 mods loaded, 155 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	AppleMilkCore{1.1.0} [AppleMilkCore] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-427-GTNH-pre} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.3.4} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	InputFix{1.7.10-v6} [InputFix] (minecraft.jar) 
	UCHIJAAAA	LumySkinPatch{1.0.13} [Lumy Skin Patch] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{2.4.9-GTNH} [NotEnoughItems] (NotEnoughItems-2.4.9-GTNH.jar) 
	UCHIJAAAA	PotionExtensionCore{1.7.10-1.1.0} [PotionExtensionCore] (minecraft.jar) 
	UCHIJAAAA	redirectionor{1.7.10} [Redirectionor] (minecraft.jar) 
	UCHIJAAAA	smoothfontcore{1.7.10-1.15.1} [Smooth Font Core] (minecraft.jar) 
	UCHIJAAAA	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCHIJAAAA	xaerominimap_core{1.7.10-1.0} [XaeroMinimapCore] (minecraft.jar) 
	UCHIJAAAA	xaeroworldmap_core{1.7.10-1.0} [XaeroWorldMapCore] (minecraft.jar) 
	UCHIJAAAA	chunkapicore{0.5.1} [ChunkAPI Core] (minecraft.jar) 
	UCHIJAAAA	endlessids_biome{1.5.3} [EndlessIDs Biome Module] (minecraft.jar) 
	UCHIJAAAA	endlessids_blockitem{1.5.3} [EndlessIDs BlockItem Module] (minecraft.jar) 
	UCHIJAAAA	endlessids_datawatcher{1.5.3} [EndlessIDs DataWatcher Module] (minecraft.jar) 
	UCHIJAAAA	endlessids_enchantment{1.5.3} [EndlessIDs Enchantment Module] (minecraft.jar) 
	UCHIJAAAA	endlessids_potion{1.5.3} [EndlessIDs Potion Module] (minecraft.jar) 
	UCHIJAAAA	OpenModsCore{0.10.1} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	FoamFixCore{1.0.4} [FoamFixCore] (minecraft.jar) 
	UCHIJAAAA	FastCraft{1.25} [FastCraft] (fastcraft-1.25.jar) 
	UCHIJAAAA	smoothfont{1.7.10-1.15.3} [Smooth Font] (SmoothFont-1.7.10-1.15.3.jar) 
	UCHIJAAAA	asjpatcher{1.0} [asjpatcher] (1.7.10-ASJCore-1.2.4.0.jar) 
	UCHIJAAAA	Prioritiser{0.1.1} [Prioritiser] (1.7.10-prioritiser-0.1.1.jar) 
	UCHIJAAAA	jewelrycraft2{1.1.4} [Jewelrycraft 2] (1.7.10] Jewelrycraft2-1.1.4-universal.jar) 
	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAA	StartingInventory{1.7.10.r03} [StartingInventory] (1.7.10]StartingInventory-universal-1.7.10.r03.jar) 
	UCHIJAAAA	miners{v3.1.1} [Miner's Heaven] (1.7.10矿工天堂[汉化]v3.1.1.jar) 
	UCHIJAAAA	unimixins{0.1.17} [UniMixins] (_+unimixins-all-1.7.10-0.1.17.jar) 
	UCHIJAAAA	unimixins-mixin{0.1.17} [UniMixins: Mixin (UniMix)] (_+unimixins-all-1.7.10-0.1.17.jar) 
	UCHIJAAAA	unimixins-compat{0.1.17} [UniMixins: Compatibility] (_+unimixins-all-1.7.10-0.1.17.jar) 
	UCHIJAAAA	mixingasm{0.3} [UniMixins: Mixingasm] (_+unimixins-all-1.7.10-0.1.17.jar) 
	UCHIJAAAA	spongemixins{2.0.1} [UniMixins: SpongeMixins] (_+unimixins-all-1.7.10-0.1.17.jar) 
	UCHIJAAAA	mixinbooterlegacy{1.2.1} [UniMixins: MixinBooterLegacy] (_+unimixins-all-1.7.10-0.1.17.jar) 
	UCHIJAAAA	gasstation{0.5.1} [UniMixins: GasStation] (_+unimixins-all-1.7.10-0.1.17.jar) 
	UCHIJAAAA	gtnhmixins{2.2.0} [UniMixins: GTNHMixins] (_+unimixins-all-1.7.10-0.1.17.jar) 
	UCHIJAAAA	mixinextras{0.1.17} [UniMixins: MixinExtras] (_+unimixins-all-1.7.10-0.1.17.jar) 
	UCHIJAAAA	MysteriumLib{1.5.2} [§5Mysterium§aLib ] (_MysteriumLib-1.5.2.jar) 
	UCHIJAAAA	achievementdetection{1.0.0} [Achievement Detection Fix] (ADFix-1.0.0.jar) 
	UCHIJAAAA	magcore{1.5.6.3} [MagCore] (MagCore-1.5.6.3.jar) 
	UCHIJAAAA	Baubles{1.3.0} [Baubles] (Baubles Rebuild-1.3.0 - 1.5.6.3.jar) 
	UCHIJAAAA	adventurebackpack{1.7.10-0.8d} [Adventure Backpack] (adventurebackpack-1.7.10-0.8e-ns.jar) 
	UCHIJAAAA	aiimprovements{0.0.1.19} [AI Improvements] (AIImprovements-1.7.10-0.0.1b19-dev.jar) 
	UCHIJAAAA	alternatecurrent{1.0} [alternatecurrent] (Alternate Current-1.4.0.jar) 
	UCHIJAAAA	AppleCore{3.1.1} [AppleCore] (AppleCore-mc1.7.10-3.1.1.jar) 
	UCHIJAAAA	DCsAppleMilk{1.7.10_2.9n} [Apple&Milk&Tea!] (AppleMilkTea2-1.7.10_2.9n.jar) 
	UCHIJAAAA	DCsNEIPluginAMT{1.7.10_1.0a} [NEIPluginForAMT] (AppleMilkTea2-1.7.10_2.9n.jar) 
	UCHIJAAAA	gtnhlib{0.4.3} [GTNH Lib] (gtnhlib-0.4.3.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-427-GTNH-pre} [Applied Energistics 2] (appliedenergistics2-rv3-beta-427-GTNH-pre.jar) 
	UCHIJAAAA	archaicfix{0.7.4} [ArchaicFix] (archaicfix-0.7.4.jar) 
	UCHIJAAAA	aura{unspecified} [Aura Cascade] (AuraCascade-557.jar) 
	UCHIJAAAA	BetterAchievements{0.2.0} [Better Achievements] (BetterAchievements-0.2.0.jar) 
	UCHIJAAAA	betterbuilderswands{0.8.1} [Better Builder's Wands] (BetterBuildersWands-0.8.1-1.7.10r92+aec06c3.jar) 
	UCHIJAAAA	bettersprinting{2.3.0} [Better Sprinting] (BetterSprinting-1.7.10-v2.3.0.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAA	Botania{r1.8-249} [Botania] (Botania+r1.8-249.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	UCHIJAAAA	bugtorch{1.2.8} [BugTorch] (bugtorch-1.2.8.jar) 
	UCHIJAAAA	BuildCraft|Core{7.1.25} [BuildCraft] (buildcraft-7.1.25.jar) 
	UCHIJAAAA	BuildCraft|Builders{7.1.25} [BC Builders] (buildcraft-7.1.25.jar) 
	UCHIJAAAA	BuildCraft|Robotics{7.1.25} [BC Robotics] (buildcraft-7.1.25.jar) 
	UCHIJAAAA	BuildCraft|Silicon{7.1.25} [BC Silicon] (buildcraft-7.1.25.jar) 
	UCHIJAAAA	BuildCraft|Energy{7.1.25} [BC Energy] (buildcraft-7.1.25.jar) 
	UCHIJAAAA	BuildCraft|Transport{7.1.25} [BC Transport] (buildcraft-7.1.25.jar) 
	UCHIJAAAA	BuildCraft|Factory{7.1.25} [BC Factory] (buildcraft-7.1.25.jar) 
	UCHIJAAAA	IC2{2.2.827-experimental} [IndustrialCraft 2] (industrialcraft-2-2.2.827-experimental.jar) 
	UCHIJAAAA	Forestry{4.2.16.64} [Forestry for Minecraft] (forestry_1.7.10-4.2.16.64.jar) 
	UCHIJAAAA	BuildCraft|Compat{7.1.8} [BuildCraft Compat] (buildcraft-compat-7.1.8.jar) 
	UCHIJAAAA	falsepatternlib{1.4.0} [FalsePatternLib] (falsepatternlib-mc1.7.10-1.4.0.jar) 
	UCHIJAAAA	chunkapi{0.5.1} [ChunkAPI] (chunkapi-mc1.7.10-0.5.1.jar) 
	UCHIJAAAA	cookiecore{1.4.0} [Cookie Core] (CookieCore-1.7.10-1.4.0-11.jar) 
	UCHIJAAAA	coretweaks{0.3.3.2} [CoreTweaks] (CoreTweaks-1.7.10-0.3.3.2+nomixin.jar) 
	UCHIJAAAA	CraftHeraldry{1.1.3} [CraftHeraldry] (CraftHeraldry+1.1.3.jar) 
	UCHIJAAAA	damagemark{2.3} [DamageMark] (DamageMarkMod-1.7.10-2.3.jar) 
	UCHIJAAAA	dmod{1.0.3.5} [D-Mod] (DMod-1.7.10-1.0.3.5.jar) 
	UCHIJAAAA	dldungeonsjdg{1.11.0.1} [Doomlike Dungeons] (DoomlikeDungeons-1.11.0.1-MC1.7.10.jar) 
	UCHIJAAAA	watermod{1.0} [watermod] (DWA_a1.jar) 
	UCHIJAAAA	entityculling{1.0.1} [Entity Culling Unofficial] (EC-Unofficial-1.0.1.jar) 
	UCHIJAAAA	EMT{1.2.6.2} [Electro-Magic Tools] (ElectroMagicTools-1.2.6.2[1.7.10].jar) 
	UCHIJAAAA	etfuturum{2.5.1} [§5§oEt Futurum Requiem] (Et_Futurum_Requiem-2.5.1.jar) 
	UCHIJAAAA	Roguelike{1.5.0} [Roguelike Dungeons] (roguelike-1.7.10-1.5.0b.jar) 
	UCHIJAAAA	enderlicious{Enderlicious} [§5Enderlicious] (enderlicious-1.1.2.jar) 
	UCHIJAAAA	endlessids{1.5.3} [EndlessIDs] (endlessids-mc1.7.10-1.5.3.jar) 
	UCHIJAAAA	evilcraft{0.9.13} [EvilCraft] (EvilCraft-1.7.10-0.9.13.jar) 
	UCHIJAAAA	exnihilo{1.38-53} [Ex Nihilo] (Ex-Nihilo-1.38-53.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (ExtraUtilities-1.2.12.jar.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	exastrisrebirth{MC1.7.10-1.01-45} [Ex Astris Rebirth] (Ex-Astris-Rebirth-MC1.7.10-1.01-45.jar) 
	UCHIJAAAA	excompressum{1.2.0} [Ex Compressum] (excompressum-mc1.7.10-1.2.0.jar) 
	UCHIJAAAA	ExtraBotany{r1.0-21} [ExtraBotany] (ExtraBotany-1.7.10-r1.0-21.jar) 
	UCHIJAAAA	ExtraTiC{1.4.6} [ExtraTiC] (ExtraTiC-1.7.10-1.4.6.jar) 
	UCHIJAAAA	ezstorage{1.1.0} [EZ Storage] (ezstorage-1.1.0.jar) 
	UCHIJAAAA	fastleafdecay{1.4} [Fast Leaf Decay] (FastLeafDecay-1.7.10-1.4.jar) 
	UCHIJAAAA	floatingitems{0.1.0} [FloatingItems] (FloatingItems-1.7.10-0.1.0.jar) 
	UCHIJAAAA	flyingcullers{1.3} [§cF§6l§ey§ai§bn§9g §fCu§7lle§8rs§r] (FlyingCullers-1.7.10-1.3.jar) 
	UCHIJAAAA	foamfix{@VERSION@} [FoamFix] (FoamFix-1.7.10-universal-1.0.4.jar) 
	UCHIJAAAA	ForgottenRelics{1.7.4} [Forgotten Relics] (ForgottenRelics-1.7.10-1.7.4.jar) 
	UCHIJAAAA	frustrator{1.1.2} [Frustrator] (Frustrator-1.7.10-1.1.2.jar) 
	UCHIJAAAA	CARuins{0.1.9} [Cellular Automata Generator] (Generatormods-0.1.9(1.7.10).jar) 
	UCHIJAAAA	GreatWallMod{0.1.9} [Great Wall Mod] (Generatormods-0.1.9(1.7.10).jar) 
	UCHIJAAAA	WalledCityMod{0.1.9} [Walled City Generator] (Generatormods-0.1.9(1.7.10).jar) 
	UCHIJAAAA	Harvest{1.7.10-1.0.0-2} [Harvest] (Harvest-1.7.10-1.0.0-2.jar) 
	UCHIJAAAA	harvest_day{Day-1} [Harvest Day] (HarvestDay-Day-1.jar) 
	UCHIJAAAA	hbm{1.0.27 BETA (5059)} [Hbm's Nuclear Tech] (HBM-NTM-[1.0.27_X5059].jar) 
	UCHIJAAAA	hodgepodge{2.5.26-pre} [Hodgepodge] (hodgepodge-2.5.26-pre.jar) 
	UCHIJAAAA	HardcoreQuesting{4.4.4} [Hardcore Questing Mode] (HQM-The Journey-4.4.4.jar) 
	UCHIJAAAA	InventoryPets{1.5.2} [Inventory Pets] (inventorypets-1.7.10-1.5.2-universal.jar) 
	UCHIJAAAA	inventorytweaks{1.59-SI-release-0421137-dirty} [Inventory Tweaks] (InventoryTweaks-1.59-unofficial-asie-1.jar) 
	UCHIJAAAA	levelup{0.10} [Level Up!] (LevelUp!-0.10(1.7.10).jar) 
	UCHIJAAAA	LunatriusCore{1.1.2.21} [LunatriusCore] (LunatriusCore-1.7.10-1.1.2.21-universal.jar) 
	UCHIJAAAA	magicalcrops{4.0.0_PUBLIC_BETA_3} [Magical Crops] (magicalcrops-4.0.0_PUBLIC_BETA_3.jar) 
	UCHIJAAAA	mjutils{1.6.1} [MJUtils] (mjutils-1.6.1.jar) 
	UCHIJAAAA	mobsnorender{0.4} [Mobs no render] (mobs-no-render-1.7.10-05.jar) 
	UCHIJAAAA	mobsinfo{0.1.3} [MobsInfo] (mobsinfo-0.1.3.jar) 
	UCHIJAAAA	mkb{2.1.0} [ModernKeyBinding] (ModernKeyBinding-Forge-1.7.10-2.1.0-mixinless.jar) 
	UCHIJAAAA	MouseTweaks{2.4.4} [Mouse Tweaks] (MouseTweaks-2.4.4-mc1.7.10.jar) 
	UCHIJAAAA	cfm{3.4.7} [?9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCHIJAAAA	neodymium{0.3.3-unofficial} [Neodymium Unofficial] (neodymium-mc1.7.10-0.3.3-unofficial.jar) 
	UCHIJAAAA	netherlicious{3.2.8} [§6Netherlicious] (netherlicious-3.2.8.jar) 
	UCHIJAAAA	recipehandler{1.7.10} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.3(1.7.10).jar) 
	UCHIJAAAA	nova_craft{1.3.3} [§3NovaCraft§5] (NovaCraft V1.3.3 (1.7.10).jar) 
	UCHIJAAAA	OpenMods{0.10.1} [OpenMods] (OpenModsLib-1.7.10-0.10.1.jar) 
	UCHIJAAAA	OpenBlocks{1.6} [OpenBlocks] (OpenBlocks-1.7.10-1.6.jar) 
	UCHIJAAAA	oreexcavation{1.1.134} [OreExcavation] (OreExcavation-1.1.134.jar) 
	UCHIJAAAA	PneumaticCraft{1.12.7-152} [PneumaticCraft] (PneumaticCraft-1.7.10-1.12.7-152-universal.jar) 
	UCHIJAAAA	polybius{b0.4} [Polybius] (Polybius-Beta.jar) 
	UCHIJAAAA	PowerUtils{1.7.10-1.0.4} [PowerUtils] (PowerUtils-1.7.10-1.0.4.jar) 
	UCHIJAAAA	runicinscription{1.0.0} [Runic Inscription] (RunicInscription-1.0.0.jar) 
	UCHIJAAAA	squidless{0.6.1} [Squidless] (squidless-1.7.10-0.6.1.jar) 
	UCHIJAAAA	Stackie{1.6.0.36} [Stackie] (Stackie-1.7.10-1.6.0.36-universal.jar) 
	UCHIJAAAA	TaintedMagic{8.1.1} [Tainted Magic] (Tainted-Magic-1.7.10-8.1.1.jar) 
	UCHIJAAAA	tc4tweak{1.5.18} [TC4 Tweak] (Thaumcraft4Tweaks-1.5.18.jar) 
	UCHIJAAAA	thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin] (thaumcraftneiplugin-1.7.10-1.7a.jar) 
	UCHIJAAAA	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) 
	UCHIJAAAA	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-53.jar) 
	UCHIJAAAA	ThaumicHorizons{1.3.5} [ThaumicHorizons] (ThaumicHorizons-1.3.5.jar) 
	UCHIJAAAA	thaumicinsurgence{0.0.2.6} [Thaumic Insurgence] (thaumicinsurgence-0.0.2.6.jar) 
	UCHIJAAAA	thaumores{1.6.0} [ThaumOres] (thaumores-1.6.0.jar) 
	UCHIJAAAA	theframework{KAMKEEL-v1} [The Framework] (TheFramework-KAMKEEL-v1.jar) 
	UCHIJAAAA	treeGrowingSimulator{0.0.3} [Tree Growing Simulator 2014] (TreeGrowingSimulator2014-MC1.7.10-0.0.3-22.jar) 
	UCHIJAAAA	aziasvendingmachine{Vending Machines Revamped} [Vending Machines Revamped] (VendingMachinesRevamped_1.1.0_1.7.10.jar) 
	UCHIJAAAA	wawla{1.3.1} [What Are We Looking At] (Wawla-1.0.5.120.jar) 
	UCHIJAAAA	weaponmod{v1.17.0} [Balkon's WeaponMod] (weaponmod-v1.17.0.jar) 
	UCHIJAAAA	XaeroMinimap{21.10.41} [Xaero's Minimap] (Xaeros_Minimap_21.10.41_Forge_1.7.10.jar) 
	UCHIJAAAA	XaeroWorldMap{1.14.1.31} [Xaero's World Map] (XaerosWorldMap_1.14.1.31_Forge_1.7.10.jar) 
	UCHIJAAAA	YAMCore{0.5.86} [YAMCore] (YAMCore-0.5.86.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	IguanaTweaksTConstruct{1.7.10-2.1.6.163} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.6.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[player_damage_hook:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: found misbehaving transformers: me.guichaguri.betterfps.transformers.MathTransformer(me.guichaguri.betterfps.transformers.MathTransformer@c9afab0) returned non-null result: 0,me.guichaguri.betterfps.transformers.EventTransformer(me.guichaguri.betterfps.transformers.EventTransformer@42abeb79) returned non-null result: 0
	AE2 Version: rv3-beta-427-GTNH-pre for Forge 10.13.4.1614
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	CPU Threads: 32
	TC4Tweak signing signature: 473C3A397676978FF4877ABA2D57860DDA20E2FC, Built by: glease
	Stencil buffer state: Function set: GL30, pool: internal, bits: 8
	Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
	AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:OFF, BuildCraftCore:ON, BuildCraftTransport:ON, BuildCraftBuilder:ON, RF:ON, RFItem:ON, CoFHWrench:ON, MFR:OFF, DSU:OFF, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:ON, GT:OFF, Chisel:OFF, Jabba:OFF, ThaumicTinkerer:ON
	Mixins in Stacktrace: 
		net.minecraft.server.MinecraftServer:
			mixins.bugtorch.early.json:minecraft.optimization.MixinMinecraftServer from mod bugtorch
			mixins.bugtorch.early.json:minecraft.fastrandom.MixinMinecraftServer from mod bugtorch
		net.minecraft.world.World:
			mixins.etfuturum.json:spectator.MixinWorld from mod etfuturum
			mixins.archaicfix.early.json:common.core.MixinWorld from mod archaicfix
			mixins.archaicfix.early.json:common.lighting.MixinWorld_Lighting from mod archaicfix
			mixins.hodgepodge.early.json:minecraft.MixinWorldLightValue from mod hodgepodge
			mixins.hodgepodge.early.json:minecraft.MixinWorld_FixXray from mod hodgepodge
			coretweaks.mixin.json:bugfix.forge5160.MixinWorld from mod coretweaks
			mixins.endlessids.json:common.blockitem.vanilla.WorldMixin from mod endlessids
			mixins.etfuturum.json:observer.MixinWorld from mod etfuturum
			mixins.hodgepodge.early.json:minecraft.MixinWorldGetBlock from mod hodgepodge
			coretweaks.mixin.json:tweak.lightfixstare.MixinWorld from mod coretweaks
			mixins.archaicfix.early.json:client.lighting.MixinWorld from mod archaicfix
			mixins.archaicfix.early.json:common.lighting.fastcraft.MixinWorld from mod archaicfix
			mixins.hodgepodge.early.json:minecraft.MixinWorld_FixAllocations from mod hodgepodge
		net.minecraft.server.integrated.IntegratedServer:
			mixins.archaicfix.early.json:client.core.MixinIntegratedServer from mod archaicfix
		net.minecraft.world.chunk.Chunk:
			mixins.endlessids.json:common.biome.vanilla.ChunkMixin from mod endlessids
			mixins.hodgepodge.early.json:minecraft.MixinChunk from mod hodgepodge
			coretweaks.mixin.json:bugfix.heightmaprange.MixinChunk from mod coretweaks
			mixins.archaicfix.early.json:common.core.MixinChunk from mod archaicfix
			mixins.archaicfix.early.json:common.lighting.MixinChunkVanilla from mod archaicfix
			mixins.etfuturum.json:observer.MixinChunk from mod etfuturum
			mixins.archaicfix.early.json:common.lighting.MixinChunk from mod archaicfix
			mixins.archaicfix.early.json:common.lighting.fastcraft.MixinChunk from mod archaicfix
			mixins.frustrator.json:client/MixinChunk from mod frustrator
			mixins.chunkapi.json:client.vanilla.ChunkMixin from mod chunkapi
			coretweaks.mixin.json:bugfix.forge5160.MixinChunk from mod coretweaks
		net.minecraft.world.WorldServer:
			mixins.hodgepodge.early.json:minecraft.MixinWorldServerUpdateEntities from mod hodgepodge
			mixins.archaicfix.early.json:common.core.MixinWorldServer from mod archaicfix
			mixins.etfuturum.json:observer.MixinWorldServer from mod etfuturum
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['gman'/3129, l='new world', x=-136.76, y=106.28, z=20.27]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 12
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 - Build 31.0.101.5187
	OpenGlRenderer: Intel(R) RaptorLake-S Mobile Graphics Controller
	OpenGlVendor: Intel
	CpuCount: 32

**Comment by brandyyn** [comment]
+1 and another person reported this same thing to me
