### ISSUE TITLE
[Compatibility Request]: Pixelmon

### ISSUE THREAD

**Issue by brandyyn** [GTMEGA/EndlessIDs#205]
### Other mod's name

Pixelmon

### Other mod's homepage

https://www.technicpack.net/modpack/enhanced-pokemon.871253

### Other mod's license

Unlicense

### Game log

[crash-2024-09-22_22.00.30-client.txt](https://github.com/user-attachments/files/17091303/crash-2024-09-22_22.00.30-client.txt)

### Description

Pixelmon crashes when checking for biome limit

java.lang.ArrayIndexOutOfBoundsException: 256
	at com.pixelmonmod.pixelmon.spawning.PixelmonBiomeDictionary.isBiomeRegistered(PixelmonBiomeDictionary.java:126)
	at com.pixelmonmod.pixelmon.spawning.PixelmonBiomeDictionary.isBiomeRegistered(PixelmonBiomeDictionary.java:119)
	at com.pixelmonmod.pixelmon.spawning.PixelmonBiomeDictionary.setupCustomBiomeTags(PixelmonBiomeDictionary.java:332)
	at com.pixelmonmod.pixelmon.Pixelmon.preInit(Pixelmon.java:106)

**Comment by KiryanEnderov** [comment]
I have this exact same error.

**Comment by KiryanEnderov** [comment]
Has this been fixed yet?

**Comment by KiryanEnderov** [comment]
Hello?

**Comment by brandyyn** [comment]
No

**Comment by KiryanEnderov** [comment]
:(

**Comment by KiryanEnderov** [comment]
@FalsePattern Whenever you're free, can you please take a look at this? I can't just remove this mod because it's one of my main mods.
