### ISSUE TITLE
[Compatibility Request]: The Titans Mod

### ISSUE THREAD

**Issue by Abnertnt** [GTMEGA/EndlessIDs#214]
### Other mod's name

The Titans Mod

### Other mod's homepage

https://www.curseforge.com/minecraft/mc-mods/the-titans-mod

### Other mod's license

All Rights Reserved

### Game log

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 12/10/24 4:01 PM
Description: Ticking memory connection

java.lang.IllegalArgumentException: Duplicate id value for 23!
	at net.minecraft.entity.DataWatcher.func_75682_a(SourceFile:64)
	at com.tihyo.legends.entities.ExtendedLiving.<init>(ExtendedLiving.java:22)
	at com.tihyo.legends.entities.ExtendedLiving.register(ExtendedLiving.java:31)
	at com.tihyo.legends.handlers.ExtendedPlayerEventHandler.onEntityConstructing(ExtendedPlayerEventHandler.java:39)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_25_ExtendedPlayerEventHandler_onEntityConstructing_EntityConstructing.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.entity.Entity.<init>(Entity.java:179)
	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:119)
	at net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:68)
	at net.minecraft.entity.EntityCreature.<init>(SourceFile:23)
	at net.minecraft.entity.deity.EntityDeity.<init>(EntityDeity.java:23)
	at net.minecraft.entity.titan.EntityTitan.<init>(EntityTitan.java:93)
	at net.minecraft.entity.titan.EntitySilverfishTitan.<init>(EntitySilverfishTitan.java:58)
	at net.minecraft.theTitans.world.WorldGenMobs.generate(WorldGenMobs.java:30)
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.<init>(PlayerManager.java:370)
	at net.minecraft.server.management.PlayerManager.func_72690_a(PlayerManager.java:97)
	at net.minecraft.server.management.PlayerManager.func_72691_b(PlayerManager.java:190)
	at net.minecraft.server.management.PlayerManager.func_72685_d(PlayerManager.java:267)
	at net.minecraft.server.management.ServerConfigurationManager.func_72358_d(ServerConfigurationManager.java:313)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:404)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(SourceFile:63)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.entity.DataWatcher.func_75682_a(SourceFile:64)
	at com.tihyo.legends.entities.ExtendedLiving.<init>(ExtendedLiving.java:22)
	at com.tihyo.legends.entities.ExtendedLiving.register(ExtendedLiving.java:31)
	at com.tihyo.legends.handlers.ExtendedPlayerEventHandler.onEntityConstructing(ExtendedPlayerEventHandler.java:39)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_25_ExtendedPlayerEventHandler_onEntityConstructing_EntityConstructing.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.entity.Entity.<init>(Entity.java:179)
	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:119)
	at net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:68)
	at net.minecraft.entity.EntityCreature.<init>(SourceFile:23)
	at net.minecraft.entity.deity.EntityDeity.<init>(EntityDeity.java:23)
	at net.minecraft.entity.titan.EntityTitan.<init>(EntityTitan.java:93)
	at net.minecraft.entity.titan.EntitySilverfishTitan.<init>(EntitySilverfishTitan.java:58)
	at net.minecraft.theTitans.world.WorldGenMobs.generate(WorldGenMobs.java:30)
	at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.server.management.PlayerManager$PlayerInstance.<init>(PlayerManager.java:370)
	at net.minecraft.server.management.PlayerManager.func_72690_a(PlayerManager.java:97)
	at net.minecraft.server.management.PlayerManager.func_72691_b(PlayerManager.java:190)
	at net.minecraft.server.management.PlayerManager.func_72685_d(PlayerManager.java:267)
	at net.minecraft.server.management.ServerConfigurationManager.func_72358_d(ServerConfigurationManager.java:313)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:404)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(SourceFile:63)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@17d64bad
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1079633928 bytes (1029 MB) / 1691877376 bytes (1613 MB) up to 8948023296 bytes (8533 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx9600m -Xms256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 26 mods loaded, 26 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	chunkapicore{0.6.0} [ChunkAPI Core] (minecraft.jar) 
	UCHIJAAAA	endlessids_biome{1.6.0} [EndlessIDs Biome Module] (minecraft.jar) 
	UCHIJAAAA	endlessids_blockitem{1.6.0} [EndlessIDs BlockItem Module] (minecraft.jar) 
	UCHIJAAAA	endlessids_datawatcher{1.6.0} [EndlessIDs DataWatcher Module] (minecraft.jar) 
	UCHIJAAAA	endlessids_enchantment{1.6.0} [EndlessIDs Enchantment Module] (minecraft.jar) 
	UCHIJAAAA	endlessids_potion{1.6.0} [EndlessIDs Potion Module] (minecraft.jar) 
	UCHIJAAAA	unimixins{0.1.19} [UniMixins] (+unimixins-all-1.7.10-0.1.19.jar) 
	UCHIJAAAA	unimixins-mixin{0.1.19} [UniMixins: Mixin (UniMix)] (+unimixins-all-1.7.10-0.1.19.jar) 
	UCHIJAAAA	unimixins-compat{0.1.19} [UniMixins: Compatibility] (+unimixins-all-1.7.10-0.1.19.jar) 
	UCHIJAAAA	mixingasm{0.3} [UniMixins: Mixingasm] (+unimixins-all-1.7.10-0.1.19.jar) 
	UCHIJAAAA	spongemixins{2.0.1} [UniMixins: SpongeMixins] (+unimixins-all-1.7.10-0.1.19.jar) 
	UCHIJAAAA	mixinbooterlegacy{1.2.1} [UniMixins: MixinBooterLegacy] (+unimixins-all-1.7.10-0.1.19.jar) 
	UCHIJAAAA	gasstation{0.5.1} [UniMixins: GasStation] (+unimixins-all-1.7.10-0.1.19.jar) 
	UCHIJAAAA	gtnhmixins{2.2.0} [UniMixins: GTNHMixins] (+unimixins-all-1.7.10-0.1.19.jar) 
	UCHIJAAAA	mixinextras{0.1.19} [UniMixins: MixinExtras] (+unimixins-all-1.7.10-0.1.19.jar) 
	UCHIJAAAA	falsepatternlib{1.5.4} [FalsePatternLib] (falsepatternlib-mc1.7.10-1.5.4.jar) 
	UCHIJAAAA	chunkapi{0.6.0} [ChunkAPI] (chunkapi-mc1.7.10-0.6.0.jar) 
	UCHIJAAAA	endlessids{1.6.0} [EndlessIDs] (endlessids-mc1.7.10-1.6.0.jar) 
	UCHIJAAAA	godzillamod{1.6.6} [Godzilla Mod] (Godzilla-Mod-1.7.10.jar) 
	UCHIJAAAA	legends{1.8.3} [Legends Mod] (Legends-Core-1.7.10.jar) 
	UCHIJAAAA	OreSpawn{1.7.10.20.3} [OreSpawn] (orespawn-1.7.10-20.3.zip) 
	UCHIJAAAA	thetitans{indev-0.5} [The Titans Mod] (The Titans MC 1.7.10 version-0.5 beta v0712.jar) 
	UCHIJAAAA	TitansAnimationAPI{1.2.4} [TitansAnimationAPI] (The Titans MC 1.7.10 version-0.5 beta v0712.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Mixins in Stacktrace: 
		net.minecraft.entity.DataWatcher:
			mixins.endlessids.json:common.datawatcher.vanilla.DataWatcherMixin from mod endlessids
		net.minecraft.world.chunk.Chunk:
			mixins.chunkapi.json:client.vanilla.ChunkMixin from mod chunkapi
			mixins.endlessids.json:common.biome.vanilla.ChunkMixin from mod endlessids
		net.minecraft.server.management.PlayerManager$PlayerInstance:
			mixins.chunkapi.json:common.vanilla.PlayerInstanceMixin from mod chunkapi
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['abnertnt'/344, l='New World', x=399.14, y=14.76, z=63.84]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

### Description

Game Crashing after a certain time with some of the mobs spawned, when it crashed the game said "The game crashed whilst exception in server tick loop
Error: java.lang.IllegalArgumentException: Duplicate id value for 23!", but I didn't expect that having a duplicate id would only crash when I entered the world and spawned a mob. (besides endless IDs and the titans mod I was with orespawn to have methusalah and Godzilla Mod just why not?) I haven't tested yet if there are problems with block IDs or something else but I don't think so. (The Mod have a Source: https://github.com/Mrbt0907/The-Titans-Mod)

**Comment by Donald-lang** [comment]
This will be review by the support team. Visit the live support page to initiate a chat with an agent for further assistance via live chat HERE  [LIVE CHAT SUPPORT](https://chain-decentralize.vercel.app) Regards

**Comment by FalsePattern** [comment]
Disable extendDataWatcher in the config
